version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    docker:
      - image: cimg/android:2024.09
    executor: android/android
    steps:
      - checkout
      - run:
          chmod +x gradlew
      - run:
          command: ./gradlew build