version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: cimg/android:2024.09

    steps:
      - checkout
      - run:
          chmod +x gradlew
      - run:
            ls
      - run:
          command: ./gradlew build