version: 2.1

orbs:
  android: cimg/android:2024.09

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          chmod +x gradlew
      - run:
            ls
      - run:
          command: ./gradlew build